# Generated by Django 4.2.20 on 2025-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_description_form_image_submittedform'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(default='form-slug', unique=True),
        ),
    ]
