# Generated by Django 4.2.15 on 2025-05-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.CharField(default='form-slug', max_length=255, unique=True),
        ),
    ]
