# Generated by Django 4.2.20 on 2025-05-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_form_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='field_type',
            new_name='type',
        ),
    ]
