# Generated by Django 4.2.20 on 2025-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_rename_field_type_formfield_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='rating',
            field=models.TextField(blank=True),
        ),
    ]
