# Generated by Django 4.2.20 on 2025-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_form_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('yesno', 'Yes/No'), ('rating', 'Rating')], max_length=10),
        ),
    ]
