# Generated by Django 4.2.20 on 2025-06-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_formfield_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='form_uploads/'),
        ),
    ]
