# Generated by Django 4.2.20 on 2025-06-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_submittedform_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedform',
            old_name='image',
            new_name='imageUrl',
        ),
    ]
