# Generated by Django 4.2.20 on 2025-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_rename_image_submittedform_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedform',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='submittedform',
            name='contentUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
