# Generated by Django 4.2.20 on 2025-06-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_remove_submittedform_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedform',
            name='contentUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
