# Generated by Django 4.2.20 on 2025-05-18 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_password_set_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_mantelzorger',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mantelzorger',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mantelzorger'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('caregiver', 'Caregiver'), ('patient', 'Patient'), ('mantelzorger', 'Mantelzorger')], default='patient', max_length=16),
        ),
    ]
