# Generated by Django 4.2.20 on 2025-05-18 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_mantelzorger_user_mantelzorger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_mantelzorger',
            new_name='email_supporter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mantelzorger',
        ),
        migrations.AddField(
            model_name='user',
            name='supporter',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'supporter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('caregiver', 'Caregiver'), ('patient', 'Patient'), ('supporter', 'Supporter')], default='patient', max_length=16),
        ),
    ]
