# Generated by Django 4.2.20 on 2025-06-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_email_mantelzorger_user_email_supporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='caregiver_id',
        ),
    ]
