# Generated by Django 4.2.20 on 2025-06-21 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_user_caregiver_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="caregiver",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "caregiver"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caregiving_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="supporter",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "supporter"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supporter_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
