# Generated by Django 4.2.20 on 2025-06-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_caregiver_alter_user_supporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forms",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
