# Generated by Django 4.2.20 on 2025-06-21 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_forms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="caregiver",
        ),
        migrations.AddField(
            model_name="user",
            name="caregiver",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "caregiver"},
                null=True,
                related_name="caregiving_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
