# Generated by Django 4.2.20 on 2025-06-21 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_user_caregiver_user_caregiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="caregiver",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "caregiver"},
                related_name="caregiving_patients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
