# Generated by Django 4.2.20 on 2025-06-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_caregiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bsn",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_supporter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="street_address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="supporter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zip_code",
        ),
    ]
